server:
  mode: "debug"
  address: ":8000"
  log_file_name: "log/odyssey.log"

mysql:
  dsn: "root:1234@tcp(odyssey_mysql:3306)/odyssey?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  address: "odyssey_redis:6379"
  password: "1234"
  db: 0