/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CicdDetail: typeof import('./components/cicd/cicd-detail.vue')['default']
    CicdNew: typeof import('./components/cicd/cicd-new.vue')['default']
    CicdSearch: typeof import('./components/cicd/cicd-search.vue')['default']
    CicdTable: typeof import('./components/cicd/cicd-table.vue')['default']
    CodeView: typeof import('./components/code-view/index.vue')['default']
    copy: typeof import('./components/project/ProjectCard copy.vue')['default']
    ExternalLinkPage: typeof import('./components/external-link-page/index.vue')['default']
    FillPage: typeof import('./components/fill-page/index.vue')['default']
    InternalLinkPage: typeof import('./components/internal-link-page/index.vue')['default']
    LangProvider: typeof import('./components/lang-provider/index.vue')['default']
    MainTransition: typeof import('./components/main-transition/index.vue')['default']
    NewChecklist: typeof import('./components/cicd/new-checklist.vue')['default']
    NewCicd: typeof import('./components/cicd/new-cicd.vue')['default']
    ProjectCard: typeof import('./components/project/ProjectCard.vue')['default']
    ProjectHeader: typeof import('./components/project/ProjectHeader.vue')['default']
    ProjectPage: typeof import('./components/project/ProjectPage.vue')['default']
    ProjectSearchBar: typeof import('./components/project/ProjectSearchBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceList: typeof import('./components/project/ServiceList.vue')['default']
    SvgIcon: typeof import('./components/svg-icon/index.vue')['default']
    VerifyCode: typeof import('./components/verify-code/index.vue')['default']
  }
}
